### ISSUE TITLE
Statikus analízis eszköz futtatása és jelzett hibák átnézése

### ISSUE THREAD

**Issue by XanleR** [BME-MIT-IET/iet-hf-2024-ercmanok#3]

**Comment by Utazo801** [comment]
Hozzáadtam a projektet a sonarcloud szolgáltatáshoz
Megcsináltam a szükséges lépéseket a workflow elkészítéséhez
SonarLint segítségével átnéztem a kódot.
Kijavítottam nagyobb problémákat, amiket jelzett az analízis

**Comment by szdor** [comment]
Átnéztem, igényes munka.
